import Head from "next/head";
import Image from "next/image";
import Layout from "../Components/Layout";
import Link from "next/link";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>comms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
       </Head>
      <Layout>
      <div className="container">
        <h1 className="titel">comm i guesss</h1>
        <p className="description"></p>
        <div className="grid">
          
    <h1>yooo whats upp</h1>  
            
         
         <Image src="/logo.png" alt="logo" width={800} height={500} /> 

         
        
                
            
          
  
          
        </div>
      
        
        
        </div>
        </Layout>
        
       <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" your mom "}
          <span className="logo">
            <Image src="/logo.png" alt="logo" width={72} height={35} />
          </span>
        </a>
      </footer>
      
           </div>
  );
}
